version: '3.7'

services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: swatches
            POSTGRES_PASSWORD: rauxa-swatches
    app:
        build: .
        command: npm run start:dev
        volumes:
            - .:/usr/src/app
        ports:
            - 3000:3000
        environment:
            DB_HOST: postgres
            DB_USER: swatches
            DB_PASSWORD: rauxa-swatches