version: '3.7'

services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: swatches
            POSTGRES_PASSWORD: rauxa-swatches
    app:
        build: .
        volumes:
            - ./:/usr/src/app
        environment:
            DB_HOST: postgres
            DB_USER: swatches
            DB_PASSWORD: rauxa-swatches