version: '3.7'

services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: swatches
            POSTGRES_PASSWORD: swatches
    app:
        build: ./backend
        command: npm run start:dev
        volumes:
            - ./backend:/usr/src/app
        ports:
            - 3000:3000
        environment:
            DB_HOST: postgres
            DB_USER: swatches
            DB_PASSWORD: swatches

    frontend:
        image: node
        command: yarn serve
        working_dir: /usr/src/app
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - 8080:8080